server:
  port: ${PORT:9001}

logging:
  level:
    org.atmosphere: warn

spring:
  mustache:
    check-template-location: false

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
#    url: jdbc:mariadb://116.126.158.6:3306/dataflow?useUnicode=true&characterEncoding=UTF8&useSSL=false
    url: jdbc:mariadb://116.126.158.6:3306/dataflowTest?useUnicode=true&characterEncoding=UTF8&useSSL=false
    username: lawshop
    password: znzn2753@

  jpa:
    open-in-view: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
      use-new-id-generator-mappings: false
      ddl-auto: update
    show_sql: true
    generate-ddl: false
    properties:
      hibernate.format_sql: true
    defer-datasource-initialization: true

# Launch the default browser when starting the application in development mode
vaadin:
  launch-browser: true

# To improve the performance during development.
# For more information https://vaadin.com/docs/flow/spring/tutorial-spring-configuration.html#special-configuration-parameters
  whitelisted-packages: com.vaadin,org.vaadin,dev.hilla,com.example.application
